import type { AppSettings, Experiment, StudentProject } from "./types";
import { createId } from "./ids";

export const TASTE_TAGS = [
  "더 맵게",
  "덜 맵게",
  "더 진하게",
  "더 순하게",
  "향 추가",
  "현재가 좋음",
];

export const defaultSettings: AppSettings = {
  version: 1,
  className: "라면 R&D 연구소",
  studentCount: 30,
  testCount: 4,
  tastingNoodleFraction: 0.25,
  updatedAt: new Date(0).toISOString(),
  ingredients: [
    {
      id: "base-broth",
      name: "기본 육수분말",
      displayName: "기본스프",
      category: "기본맛",
      imageUrl: "",
      defaultAmount: 1.5,
      minAmount: 0,
      maxAmount: 3,
      step: 0.5,
      purchasePrice: 8900,
      purchaseWeight: 500,
      allergen: "밀, 대두",
      enabled: true,
      order: 1,
    },
    {
      id: "spicy-base",
      name: "매운맛 시즈닝",
      displayName: "매운맛",
      category: "매운맛",
      imageUrl: "",
      defaultAmount: 0.5,
      minAmount: 0,
      maxAmount: 2,
      step: 0.5,
      purchasePrice: 7200,
      purchaseWeight: 300,
      allergen: "대두",
      enabled: true,
      order: 2,
    },
    {
      id: "garlic-powder",
      name: "마늘분말",
      displayName: "마늘향",
      category: "향미",
      imageUrl: "",
      defaultAmount: 0,
      minAmount: 0,
      maxAmount: 1.5,
      step: 0.5,
      purchasePrice: 6100,
      purchaseWeight: 250,
      allergen: "없음",
      enabled: true,
      order: 3,
    },
    {
      id: "onion-powder",
      name: "양파분말",
      displayName: "양파맛",
      category: "향미",
      imageUrl: "",
      defaultAmount: 0,
      minAmount: 0,
      maxAmount: 1.5,
      step: 0.5,
      purchasePrice: 5900,
      purchaseWeight: 250,
      allergen: "없음",
      enabled: true,
      order: 4,
    },
    {
      id: "umami",
      name: "감칠맛 시즈닝",
      displayName: "감칠맛",
      category: "감칠맛",
      imageUrl: "",
      defaultAmount: 0.5,
      minAmount: 0,
      maxAmount: 1.5,
      step: 0.5,
      purchasePrice: 7900,
      purchaseWeight: 400,
      allergen: "밀, 대두",
      enabled: true,
      order: 5,
    },
  ],
  toppings: [
    {
      id: "green-onion",
      name: "건조 대파",
      displayName: "대파",
      imageUrl: "",
      amountPerStudent: 1,
      purchasePrice: 8500,
      purchaseWeight: 200,
      allergen: "없음",
      enabled: true,
      order: 1,
    },
    {
      id: "dried-vegetable",
      name: "건조 야채믹스",
      displayName: "야채믹스",
      imageUrl: "",
      amountPerStudent: 2,
      purchasePrice: 12000,
      purchaseWeight: 500,
      allergen: "대두",
      enabled: true,
      order: 2,
    },
  ],
  supplies: [
    {
      id: "noodle",
      name: "사리면",
      category: "noodle",
      vendorNote: "",
      purchasePrice: 10000,
      purchaseQuantity: 20,
      unit: "개",
      quantityPerStudent: 2,
      fixedQuantity: 0,
      enabled: true,
      order: 1,
    },
    {
      id: "tasting-cup",
      name: "시식컵",
      category: "tasting",
      vendorNote: "",
      purchasePrice: 5000,
      purchaseQuantity: 100,
      unit: "개",
      quantityPerStudent: 4,
      fixedQuantity: 0,
      enabled: true,
      order: 2,
    },
    {
      id: "final-bowl",
      name: "무지 라면용기",
      category: "container",
      vendorNote: "",
      purchasePrice: 12000,
      purchaseQuantity: 50,
      unit: "개",
      quantityPerStudent: 1,
      fixedQuantity: 0,
      enabled: true,
      order: 3,
    },
    {
      id: "soup-pouch",
      name: "스프 소분팩",
      category: "consumable",
      vendorNote: "",
      purchasePrice: 3000,
      purchaseQuantity: 100,
      unit: "개",
      quantityPerStudent: 1,
      fixedQuantity: 0,
      enabled: true,
      order: 4,
    },
    {
      id: "topping-pouch",
      name: "건더기 소분팩",
      category: "consumable",
      vendorNote: "",
      purchasePrice: 3000,
      purchaseQuantity: 100,
      unit: "개",
      quantityPerStudent: 1,
      fixedQuantity: 0,
      enabled: true,
      order: 5,
    },
    {
      id: "label-paper",
      name: "라벨지",
      category: "consumable",
      vendorNote: "",
      purchasePrice: 5000,
      purchaseQuantity: 100,
      unit: "매",
      quantityPerStudent: 1,
      fixedQuantity: 0,
      enabled: true,
      order: 6,
    },
    {
      id: "gloves",
      name: "위생장갑",
      category: "tool",
      vendorNote: "",
      purchasePrice: 8000,
      purchaseQuantity: 200,
      unit: "장",
      quantityPerStudent: 2,
      fixedQuantity: 0,
      enabled: true,
      order: 7,
    },
    {
      id: "measuring-spoon",
      name: "계량스푼",
      category: "tool",
      vendorNote: "모둠별 1세트",
      purchasePrice: 6000,
      purchaseQuantity: 10,
      unit: "개",
      quantityPerStudent: 0,
      fixedQuantity: 8,
      enabled: true,
      order: 8,
    },
  ],
  safetyChecks: [
    "수업 전 모든 학생의 식품 알레르기를 확인했다.",
    "뜨거운 물은 교사가 제공하고 학생이 직접 운반하지 않는다.",
    "시식 전 손 씻기와 위생장갑 착용을 확인한다.",
    "사용 재료의 소비기한과 보관 상태를 확인한다.",
    "시식컵이 뜨거울 때는 지정된 자리에서 충분히 식힌다.",
  ],
};

export function blankExperiment(settings: AppSettings): Experiment {
  return {
    recipe: Object.fromEntries(
      settings.ingredients.map((ingredient) => [
        ingredient.id,
        ingredient.enabled ? ingredient.defaultAmount : 0,
      ]),
    ),
    note: "",
    tags: [],
    saved: false,
  };
}

export function createStudentProject(
  settings: AppSettings,
  id = createId("student"),
): StudentProject {
  return {
    id,
    studentName: "",
    teamName: "",
    experiments: Array.from({ length: settings.testCount }, () =>
      blankExperiment(settings),
    ),
    bestRecipeIndex: null,
    label: { productName: "", tasteLine: "", developerName: "" },
    updatedAt: new Date().toISOString(),
  };
}

export function normalizeProject(
  project: StudentProject,
  settings: AppSettings,
): StudentProject {
  const experiments = Array.from({ length: settings.testCount }, (_, index) => {
    const previous = project.experiments[index] ?? blankExperiment(settings);
    return {
      ...previous,
      recipe: Object.fromEntries(
        settings.ingredients.map((ingredient) => [
          ingredient.id,
          previous.recipe[ingredient.id] ?? ingredient.defaultAmount,
        ]),
      ),
    };
  });

  return { ...project, experiments };
}
